### ISSUE TITLE
Position cannot be changed

### ISSUE THREAD

**Issue by jtenos** [luthraG/image-watermark#2]
Looks like the default value for position cannot be changed - the code sets it to null, then checks to see if it's empty before setting it to the default of Center.

Would it make sense to allow the caller to define a position? Like:

`var position = options.position,`

instead of

`var position = null,`

This may not make sense for some of the alignments, but for a "ltr" alignment, it would be nice to be able to position on one of the corners.

**Comment by prio101** [comment]
this issue has been solved in this pull request #10

**Comment by jtenos** [comment]
Closing since this was solved in a separate pull request
